name: "Tesla Local Commands"
version: "0.0.10f"
slug: "tesla_local_commands"
description: "Local BLE calls to control your Tesla."
url: "https://github.com/tesla-local-control/tesla-local-control-addon"
stage: experimental
host_network: true
host_dbus: true
# homeassistant_api: true
privileged: [NET_ADMIN]
arch:
  - aarch64
  - amd64
hassio_role: homeassistant
init: false
map:
  - share:rw
startup: services
options:
  vin: ""
  vin_list: ""
  ble_mac: ""
  ble_mac_list: ""
  presence_detection_ttl: 180
  debug: false
  mqtt_ip: ""
  mqtt_port: "1883"
  mqtt_user: ""
  mqtt_pwd: ""
  send_cmd_retry_delay: "5"

schema:
  vin: str?
  vin_list: "match(^([A-HJ-NPR-Z0-9]{17})(\|[A-HJ-NPR-Z0-9]{17})*$)"
  ble_mac:str?
  ble_mac_list: "match(^([0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5})(\|[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5})*$)?"
  presence_detection_ttl: "int(0,)"
  debug: bool
  mqtt_ip: str
  mqtt_port: str?
  mqtt_user: str?
  mqtt_pwd: password?
  send_cmd_retry_delay: "int(1,)"
# ingress: true
# panel_icon: mdi:forward
# backup_exclude:
  # - /data/gnugpg
  # - /data/password-store
# hassio_api: true
