name: "Tesla Local Commands"
version: "0.0.8a"
slug: "tesla_local_commands"
description: "Local BLE calls to control your Tesla."
# url: "tbc"
stage: experimental
host_network: true
host_dbus: true
# homeassistant_api: true
privileged: [NET_ADMIN]
arch:
  - aarch64
  - amd64
hassio_role: homeassistant
init: false
# full_access: true
map:
  - share:rw
startup: services
options:
  vin: ""
  debug: false
  mqtt_ip: ""
  mqtt_port: "1883"
  mqtt_user: ""
  mqtt_pwd: ""
  send_cmd_retry_delay: "5"
  ble_presence_enable: true
schema:
  vin: str?
  debug: bool
  mqtt_ip: str?
  mqtt_port: str?
  mqtt_user: str?
  mqtt_pwd: password?
  send_cmd_retry_delay: str?
  ble_presence_enable: bool
# ingress: true
# panel_icon: mdi:forward
# backup_exclude:
  # - /data/gnugpg
  # - /data/password-store
# hassio_api: true
