volumes:
  tesla_ble_mqtt:
    external: true

services:   
  tesla_ble_mqtt:
    container_name: tesla_ble_mqtt

    stdin_open: true
    tty: true    
    
    entrypoint: "[ -L /command/with-contenv ] \
                  && /app/run.sh \
                  || /usr/bin/sh /app/run.sh"

    working_dir: /data
    
    volumes:
      - tesla_ble_mqtt:/data
      - /run/dbus:/run/dbus
      - ~/share/tesla_ble_mqtt:/share/tesla_ble_mqtt
        
    network_mode: host
    privileged: true 

    restart: no
    #restart: unless-stopped  
